name: python compatibility

on:
  push:
    branches:
      - python-compatibility
    paths-ignore:
      - '**/README.md'
      - 'examples/**'
      - 'test/**'
      - 'c_src/**'
      - 'lib/**'
      - 'patches/**'
      - 'nerves/**'
      - 'cc_toolchain/**'
      - '.github/FUNDING.yml'
      - '.github/workflows/nerves-*'
      - '.github/workflows/macos-*'
      - '.github/workflows/linux-*'

  workflow_dispatch:

jobs:
  python_compatibility:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      OPENCV_VER: "4.6.0"

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v2

      - name: Set up beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "24.1.5"
          elixir-version: "1.13"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python --version

      - name: Install system dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake autoconf pkg-config bc m4 unzip zip curl git libssl-dev libncurses5-dev erlang-inets erlang-os-mon erlang-runtime-tools erlang-ssl erlang-dev ca-certificates
          sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavresample-dev ffmpeg

      - name: Mix Compile
        run: |
          mix deps.get
          mix compile

      - name: Mix Test
        run: |
          mix test --include dnn
